<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="3" hostname="ADMINRG-BGRV2NO" name="TestNG.Assignment" tests="5" failures="1" timestamp="31 Jan 2021 16:19:12 GMT" time="8.615" errors="0">
  <testcase name="dashBoardHeading" time="0.769" classname="TestNG.Assignment">
    <failure type="java.lang.AssertionError" message="expected [xys] but found [Dashboard]">
      <![CDATA[java.lang.AssertionError: expected [xys] but found [Dashboard]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at TestNG.Assignment.dashBoardHeading(Assignment.java:97)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:958)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1160)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:753)
	at org.testng.TestRunner.run(TestRunner.java:607)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:368)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:363)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:321)
	at org.testng.SuiteRunner.run(SuiteRunner.java:270)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1284)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1209)
	at org.testng.TestNG.runSuites(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1096)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- dashBoardHeading -->
  <testcase name="dashBoardHeading" time="0.731" classname="TestNG.Assignment">
    <skipped/>
  </testcase> <!-- dashBoardHeading -->
  <testcase name="dashBoardHeading" time="0.714" classname="TestNG.Assignment">
    <skipped/>
  </testcase> <!-- dashBoardHeading -->
  <testcase name="dashBoardHeading" time="0.869" classname="TestNG.Assignment">
    <skipped/>
  </testcase> <!-- dashBoardHeading -->
  <testcase name="login" time="5.532" classname="TestNG.Assignment"/>
</testsuite> <!-- TestNG.Assignment -->
